# Generated by Django 5.2.8 on 2026-02-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FolderCache',
            fields=[
                ('folder_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('parent_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=512)),
                ('path', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'folder_cache',
            },
        ),
        migrations.CreateModel(
            name='SearchResultCache',
            fields=[
                ('query_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('query_text', models.TextField()),
                ('results_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'search_result_cache',
            },
        ),
        migrations.CreateModel(
            name='SynonymCache',
            fields=[
                ('word', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('synonyms_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'synonym_cache',
            },
        ),
    ]
